name: PR Merge Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:
      - "main"

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  pr-validation:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Get the last commit message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git show -s --format=%s)
          echo "Commit message: $COMMIT_MESSAGE"
          echo "message=${COMMIT_MESSAGE}" >> ${GITHUB_OUTPUT}

      - name: Commit Message Check
        shell: bash
        run: |-
          if [[ "${{ steps.commit_message.outputs.message }}" != *"fix:"* || "${{ steps.commit_message.outputs.message }}" != *"feat:"* ]]; then
            echo "Commit message does not contain required keywords."
            exit 1
          fi