name: CICD Build

on:
  push:
    branches:
      - "main"

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  clone:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false